### ISSUE TITLE
build: error fetching release

### ISSUE THREAD

**Issue by echlebek** [SumoLogic/sumologic-otel-collector-packaging#79]
Sometimes, the installation script test runner will fail to set up, saying:

```
make: *** [test] Error 1
error fetching release: failed to get release: 403 Forbidden
```

Re-running the job will often result in the problem going away.

**Comment by echlebek** [comment]
Fixed in #80

**Comment by echlebek** [comment]
Per @amdprophet,

![image](https://github.com/SumoLogic/sumologic-otel-collector-packaging/assets/1633772/03fdbfd0-5e33-46b7-b017-84f229253572)

Looks like we need to add auth to https://github.com/SumoLogic/sumologic-otel-collector-packaging/blob/main/install-script/test/consts_common.go#L21

**Comment by harshshahsumo** [comment]
should we close this?
